# Generated by Django 2.2.7 on 2020-01-06 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_added_date', models.DateTimeField()),
                ('file_type', models.CharField(max_length=128)),
                ('file_size', models.IntegerField()),
                ('file_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_added', models.DateTimeField()),
                ('job_started', models.DateTimeField()),
                ('job_finished', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_profile_name', models.CharField(max_length=255)),
                ('material_profile_description', models.TextField(blank=True, null=True)),
                ('material_profile_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_name', models.CharField(max_length=255)),
                ('printer_description', models.TextField(blank=True, null=True)),
                ('printer_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('printer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('printer_apikey', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_username', models.CharField(blank=True, max_length=255, null=True)),
                ('printer_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlicerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slicer_profile_name', models.CharField(max_length=255)),
                ('slicer_profile_description', models.TextField(blank=True, null=True)),
                ('slicer_profile_printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.Printer')),
            ],
        ),
        migrations.CreateModel(
            name='SlicerProfileSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slicer_profile_setting_key', models.CharField(max_length=128)),
                ('slicer_profile_setting_value', models.CharField(max_length=128)),
                ('slicer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.SlicerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printer_status_from', models.DateTimeField()),
                ('printer_status_until', models.DateTimeField(blank=True, null=True)),
                ('printer_status_printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.Printer')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialProfileSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_profile_setting_key', models.CharField(max_length=128)),
                ('material_profile_setting_value', models.CharField(max_length=128)),
                ('material_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.MaterialProfile')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_detail_ammount', models.IntegerField()),
                ('job_detail_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.File')),
                ('job_detail_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MATT.Job')),
            ],
        ),
    ]
